config/routes.rb
Rails.application.routes.draw do
  get 'usertasks/create'
  resources :tasks, only: :index do
  	resources :usertasks, only: :create
  end
  resources :usertasks, only: :index
  root to: 'tasks#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :usertasks
  has_many :users, through: :usertasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :usertasks
  has_many :tasks, through: :usertasks
end

app/models/usertask.rb
class Usertask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  	@tasks = Task.all
  end
end

app/controllers/usertasks_controller.rb
class UsertasksController < ApplicationController
  before_action :authenticate_user!

  def create
  	@task = Task.find(params[:task_id])
  	@usertask = Usertask.new(task: @task, user: current_user)
  	if @usertask.save
  		redirect_to tasks_path, notice: 'Has indicado que has realizado esta actividad'
  	else
  		redirect_to tasks_path alert: 'No se ha podido ingresar su orden'
  	end
  end
  def delete
    @task = Task.find(params[:task_id])
    @task.each do |task|
    task.detroy
  end    
  
  end

  def index
  	@usertask = current_user.usertasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/usertasks_helper.rb
module UsertasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= link_to "App 18", tasks_path%></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        </a>
        <div class="collapse navbar-collapse" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>

          <a class="nav-link" href="#"><%= link_to "Tareas", tasks_path%> </a>
          <a class="nav-link" href="#"><%= link_to "Tareas Realizadas", usertasks_path%> </a>

          <a class="nav-link" href="#"><%= link_to "Salir", destroy_user_session_path, method: :delete %></a>
          <% else %>
          <a class="nav-link" href="#"><%= link_to "Iniciar Sesion", new_user_session_path%></a>
          <a class="nav-link" href="#"><%= link_to "Registrarse", new_user_registration_path%></a>

          <% end %> <span class="caret"></span></a>
          <ul class="collapse navbar-collapse" role="menu">

          <% if user_signed_in?  %>
          <a> <a href="#"> <%= current_user.email %></a> </a>
          <% end %>
        </div>
      </li>

    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Septembertasks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
      <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
      <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="container">
	<div class="row">
		<% @tasks.each_slice(3) do |row| %>
		  <% row.each do |task| %>
			  <div class="col">
			  	<div class="card border bg-light">
			  		<%= image_tag task.photo,size:'350x250',class: "card-img-top" %>
			  		<div class="body">
						  <h5><%= task.name %></h5>
						  <%= link_to "Done", task_usertasks_path(task), class: 'btn btn-success', method: :post %>
						  <%= link_to "x", task_usertasks_path(task), class: 'btn btn-danger', method: :post %>
						</div>
					</div>
				</div>
			<% end %>
			<div class="w-100" style="margin-top:20px">	</div>
		<% end %>

	</div>
</div>

app/views/usertasks/create.html.erb
<h1>Usertasks#create</h1>
<p>Find me in app/views/usertasks/create.html.erb</p>

app/views/usertasks/index.html.erb
<table class="table">
	<% @usertask.each do |usertask| %>
		<tr>
			<td><%= usertask.task.name %></td>
			<td><%= usertask.user.email %></td>

		</tr>
	<% end %>
</table>